package com.yhw.alixiaohao.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yhw.alixiaohao.entity.BindTel;
import com.yhw.alixiaohao.entity.CallRecord;
import com.yhw.alixiaohao.entity.Message;
import com.yhw.alixiaohao.entity.MyUser;
import com.yhw.alixiaohao.entity.SIMStatus;
import com.yhw.alixiaohao.entity.SmallNumber;
import com.yhw.alixiaohao.entity.SpecTC;
import com.yhw.alixiaohao.entity.User;
import com.yhw.alixiaohao.entity.UserInfo;

import com.yhw.alixiaohao.entity.BindTelDao;
import com.yhw.alixiaohao.entity.CallRecordDao;
import com.yhw.alixiaohao.entity.MessageDao;
import com.yhw.alixiaohao.entity.MyUserDao;
import com.yhw.alixiaohao.entity.SIMStatusDao;
import com.yhw.alixiaohao.entity.SmallNumberDao;
import com.yhw.alixiaohao.entity.SpecTCDao;
import com.yhw.alixiaohao.entity.UserDao;
import com.yhw.alixiaohao.entity.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bindTelDaoConfig;
    private final DaoConfig callRecordDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig myUserDaoConfig;
    private final DaoConfig sIMStatusDaoConfig;
    private final DaoConfig smallNumberDaoConfig;
    private final DaoConfig specTCDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final BindTelDao bindTelDao;
    private final CallRecordDao callRecordDao;
    private final MessageDao messageDao;
    private final MyUserDao myUserDao;
    private final SIMStatusDao sIMStatusDao;
    private final SmallNumberDao smallNumberDao;
    private final SpecTCDao specTCDao;
    private final UserDao userDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bindTelDaoConfig = daoConfigMap.get(BindTelDao.class).clone();
        bindTelDaoConfig.initIdentityScope(type);

        callRecordDaoConfig = daoConfigMap.get(CallRecordDao.class).clone();
        callRecordDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        myUserDaoConfig = daoConfigMap.get(MyUserDao.class).clone();
        myUserDaoConfig.initIdentityScope(type);

        sIMStatusDaoConfig = daoConfigMap.get(SIMStatusDao.class).clone();
        sIMStatusDaoConfig.initIdentityScope(type);

        smallNumberDaoConfig = daoConfigMap.get(SmallNumberDao.class).clone();
        smallNumberDaoConfig.initIdentityScope(type);

        specTCDaoConfig = daoConfigMap.get(SpecTCDao.class).clone();
        specTCDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        bindTelDao = new BindTelDao(bindTelDaoConfig, this);
        callRecordDao = new CallRecordDao(callRecordDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        myUserDao = new MyUserDao(myUserDaoConfig, this);
        sIMStatusDao = new SIMStatusDao(sIMStatusDaoConfig, this);
        smallNumberDao = new SmallNumberDao(smallNumberDaoConfig, this);
        specTCDao = new SpecTCDao(specTCDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(BindTel.class, bindTelDao);
        registerDao(CallRecord.class, callRecordDao);
        registerDao(Message.class, messageDao);
        registerDao(MyUser.class, myUserDao);
        registerDao(SIMStatus.class, sIMStatusDao);
        registerDao(SmallNumber.class, smallNumberDao);
        registerDao(SpecTC.class, specTCDao);
        registerDao(User.class, userDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        bindTelDaoConfig.clearIdentityScope();
        callRecordDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        myUserDaoConfig.clearIdentityScope();
        sIMStatusDaoConfig.clearIdentityScope();
        smallNumberDaoConfig.clearIdentityScope();
        specTCDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public BindTelDao getBindTelDao() {
        return bindTelDao;
    }

    public CallRecordDao getCallRecordDao() {
        return callRecordDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public MyUserDao getMyUserDao() {
        return myUserDao;
    }

    public SIMStatusDao getSIMStatusDao() {
        return sIMStatusDao;
    }

    public SmallNumberDao getSmallNumberDao() {
        return smallNumberDao;
    }

    public SpecTCDao getSpecTCDao() {
        return specTCDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
