package com.yhw.alixiaohao.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SIMSTATUS".
*/
public class SIMStatusDao extends AbstractDao<SIMStatus, Long> {

    public static final String TABLENAME = "SIMSTATUS";

    /**
     * Properties of entity SIMStatus.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Account = new Property(1, String.class, "Account", false, "ACCOUNT");
        public final static Property Sim1 = new Property(2, String.class, "sim1", false, "SIM1");
        public final static Property Sim2 = new Property(3, String.class, "sim2", false, "SIM2");
    }


    public SIMStatusDao(DaoConfig config) {
        super(config);
    }
    
    public SIMStatusDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SIMSTATUS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACCOUNT\" TEXT," + // 1: Account
                "\"SIM1\" TEXT," + // 2: sim1
                "\"SIM2\" TEXT);"); // 3: sim2
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SIMSTATUS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SIMStatus entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Account = entity.getAccount();
        if (Account != null) {
            stmt.bindString(2, Account);
        }
 
        String sim1 = entity.getSim1();
        if (sim1 != null) {
            stmt.bindString(3, sim1);
        }
 
        String sim2 = entity.getSim2();
        if (sim2 != null) {
            stmt.bindString(4, sim2);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SIMStatus entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Account = entity.getAccount();
        if (Account != null) {
            stmt.bindString(2, Account);
        }
 
        String sim1 = entity.getSim1();
        if (sim1 != null) {
            stmt.bindString(3, sim1);
        }
 
        String sim2 = entity.getSim2();
        if (sim2 != null) {
            stmt.bindString(4, sim2);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SIMStatus readEntity(Cursor cursor, int offset) {
        SIMStatus entity = new SIMStatus( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Account
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sim1
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // sim2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SIMStatus entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSim1(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSim2(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SIMStatus entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SIMStatus entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SIMStatus entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
